version: "3.9"

services:
  migrate:
    image: "migrate/migrate"
    networks:
      - CRMNet
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:123321@postgres-crm-auth:5432/crm_admin_auth?sslmode=disable", "up"]
    depends_on:
      postgres-crm-auth:
        condition: service_healthy

  postgres-crm-auth:
    image: postgres:16.3
    container_name: postgres-crm-auth
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=crm_admin_auth
    networks:
      - CRMNet
    ports:
      - 5437:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  auth:
    container_name: crm-admin_auth
    build: .
    depends_on:
      postgres-crm-auth:
        condition: service_healthy
    networks:
      - CRMNet
    ports:
      - "9090:9090"

networks:
  CRMNet:
    name: CRMNet
    driver: bridge
    external: true

volumes:
  postgres_data:
    name: auth_postgres_data
  migrations: