DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS salary_adjustments;
DROP TABLE IF EXISTS staff_salary;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS branches;
DROP TABLE IF EXISTS company;

DROP TYPE IF EXISTS bonuses_type;
DROP TYPE IF EXISTS adjustment_type;
DROP TYPE IF EXISTS currency_type;
DROP TYPE IF EXISTS type_client;
DROP TYPE IF EXISTS type;
DROP TYPE IF EXISTS role;
