DROP TABLE IF EXISTS clients;
DROP TYPE IF EXISTS type_client;
DROP TYPE IF EXISTS type;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS role;
DROP TABLE IF EXISTS branches;
DROP TABLE IF EXISTS company;